### ISSUE TITLE
using say() to start baritone fails.

### ISSUE THREAD

**Issue by fw4hre0xxq** [TheIncgi/AdvancedMacros-Source#18]
MC version 1.12.2
Advanced Macros version 7.7.7b
Baritone version 1.2.11 API Forge
Forge version 14.23.5.2768

Steps to reproduce:
1. Set up fresh MC Install (I used MultiMC)
2. Install the aforementioned forge version using MultiMC
3. Install baritone-api-forge.1.2.11.jar and advancedmacros-7.7.7b.jar using MultiMC
4. Launch MC and use ingame Advanced Macros text editor to create a file containing `say("#mine diamond_ore")`
5. Observe the following error.

```17:29:42] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] > mine diamond_ore
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: baritone.api.command.exception.CommandUnhandledException: java.lang.IllegalStateException
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.cc.execute(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.a(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.x.onSendChatMessage(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ce.a(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.util.concurrent.CopyOnWriteArrayList.forEach(CopyOnWriteArrayList.java:891)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at baritone.ce.onSendChatMessage(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.handler$sendChatMessage$zze000(EntityPlayerSP.java)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at net.minecraft.client.entity.EntityPlayerSP.func_71165_d(EntityPlayerSP.java)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at com.theincgi.advancedMacros.lua.LuaFunctions$Say.call(LuaFunctions.java:58)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at org.luaj.vm2_v3_0_1.LuaClosure.execute(LuaClosure.java:357)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at org.luaj.vm2_v3_0_1.LuaClosure.onInvoke(LuaClosure.java:178)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at org.luaj.vm2_v3_0_1.LuaClosure.invoke(LuaClosure.java:171)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at com.theincgi.advancedMacros.lua.LuaDebug$LuaThread$1.run(LuaDebug.java:164)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [baritone.api.command.exception.CommandUnhandledException:handle:-1]: 	at java.lang.Thread.run(Thread.java:748)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.IllegalStateException
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.fm.<init>(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.ci.<init>(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.ci.<init>(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.fb.mine(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.api.process.IMineProcess.mine(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	at baritone.bk.execute(Unknown Source)
[17:29:42] [function: C:\Users\gnwyeh\bin\MultiMC\instances\example\.minecraft\mods\advancedMacros\macros\test:0-0/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:635]: 	... 14 more
[17:29:42] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] Mining [BlockOptionalMeta{block=Block{minecraft:diamond_ore},meta=null}]
[17:29:42] [main/INFO] [net.minecraft.client.gui.GuiNewChat]: [CHAT] [Baritone] An unhandled exception occurred. The error is in your game's log, please report this at https://github.com/cabaletta/baritone/issues```

**Comment by MajsterTynek** [comment]
You didn't specify version or port what you are using.
Try `say("#version")` or `say("@version")` or even `say(".b version")` …
You should interest in using LuaJava and use it's [official API](https://github.com/cabaletta/baritone/releasesl).
You need `standalone`+`forge`+`API` version for that.

**Comment by MajsterTynek** [comment]
@fw4hre0xxq You used version for integration, 
you need to write handler for yourself there.
Use standalone version, if you want to use chat commands.

**Comment by fw4hre0xxq** [comment]
I did some more testing. Running `say("#version)` or `say("#goto 1000 1000") works, but `say("#mine diamond_ore")` does not. manually typing `#mine diamond_ore` into chat results in the same error. I have tested this using baritone-api-forge.1.2.11.jar and  baritone-standalone-forge-1.2.11.jar. The behavior is identical.

**Comment by MajsterTynek** [comment]
Minecraft is not thread safe and Baritone protects itself from random exceptions this way.
https://github.com/cabaletta/baritone/issues/1260
https://github.com/cabaletta/baritone/issues/1521

These methods should happen on Minecraft's main thread:
https://github.com/TheIncgi/AdvancedMacros-Source/blob/b7554b281e8493b8c19c2d46d420a2f397baede2/src/main/java/com/theincgi/advancedMacros/lua/LuaFunctions.java#L55-L62
https://github.com/TheIncgi/AdvancedMacros-Source/blob/8372b22894ef354dcd94413ceb233f775c3224d3/src/main/java/com/theincgi/advancedMacros/event/ForgeEventHandler.java#L1116-L1126

`sendChatMessage` must be wrapped using `Utils.runOnMCAndWait( ()-> { /* ... */ } );`
Current workaround for macros is `runOnMC( say, "#command" )`
This issue should be fixed in future releases.
