### ISSUE TITLE
anvil broken

### ISSUE THREAD

**Issue by Lopol2010** [TheIncgi/AdvancedMacros-Source#7]
I've just installed fresh forge 28.0.55 and only this mod. I can't interact with anvil only place\break.

**Comment by Lopol2010** [comment]
Here is log, error caused by mod probably [latest.log](https://github.com/TheIncgi/AdvancedMacros-Source/files/3544446/latest.log)

**Comment by TheIncgi** [comment]
@TheIncgi 
net.minecraftforge.fml.common.ObfuscationReflectionHelper$UnableToFindMethodException: java.lang.NoSuchMethodException: net.minecraft.client.gui.screen.inventory.AnvilScreen.func_214075_a()
	at net.minecraftforge.fml.common.ObfuscationReflectionHelper.findMethod(ObfuscationReflectionHelper.java:227)
	at com.theincgi.advancedMacros.lua.functions.GuiControls$DoRepair.<init>(GuiControls.java:115)
	at com.theincgi.advancedMacros.lua.functions.GuiControls.load(GuiControls.java:53)
	at com.theincgi.advancedMacros.event.ForgeEventHandler.onGuiOpened(ForgeEventHandler.java:775)
